<a href="https://colab.research.google.com/github/ria1994maitra/Practice_Codes/blob/main/Numpy(contibued)_padhai_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Week-10**

**PANDAS(Continued)**

In [2]:
import numpy as np
import pandas as pd

## Creating Dataframe object

In [5]:
arr = np.random.randint(0,10, (5,3))

In [6]:
arr

array([[7, 4, 6],
       [2, 1, 5],
       [5, 0, 2],
       [3, 8, 0],
       [1, 3, 8]])

In [7]:
df = pd.DataFrame(arr)

In [8]:
df

0  1  2
0  7  4  6
1  2  1  5
2  5  0  2
3  3  8  0
4  1  3  8

In [9]:
df.values

array([[7, 4, 6],
       [2, 1, 5],
       [5, 0, 2],
       [3, 8, 0],
       [1, 3, 8]])

In [10]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [12]:
for c in df.columns:
    print(c)

0
1
2


In [13]:
df.values[0]

array([7, 4, 6])

In [14]:
df.index = ["R1","R2","R3","R4","R5"]
df.columns = ["C1","C2","C3"]

In [15]:
df

C1  C2  C3
R1   7   4   6
R2   2   1   5
R3   5   0   2
R4   3   8   0
R5   1   3   8

In [16]:
df.loc["R3","C2"]

0

In [17]:
df.iloc[2,1]

0

In [18]:
type(df.iloc[2:4,1:3])

pandas.core.frame.DataFrame

In [19]:
df.loc["R3":"R5","C2":"C3"]

C2  C3
R3   0   2
R4   8   0
R5   3   8

In [20]:
df.iloc[0]

C1    7
C2    4
C3    6
Name: R1, dtype: int64

In [21]:
df.iloc[:,0]

R1    7
R2    2
R3    5
R4    3
R5    1
Name: C1, dtype: int64

In [22]:
df.shape

(5, 3)

In [23]:
df.T

R1  R2  R3  R4  R5
C1   7   2   5   3   1
C2   4   1   0   8   3
C3   6   5   2   0   8

Task on Creating Dataframes

In [25]:
def create_df(nRows, nCols, maxRand = 10):
    arr = pd.random.randint(o, maxRand, (nRows, nCols))
    df = pd.DataFrame(arr)
    df.index = ["R" + str(x) for x in np.arange(1, nRows + 1)]
    df.columns = ["C" + str(x) for x in np.arange(1, nCols + 1)]
    return df