<a href="https://colab.research.google.com/github/ria1994maitra/Practice_Codes/blob/main/Padhai_Foundation_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy( Week- 8)**

## **Working with arrays**
* Scientific Computing
* Financial Analysis
* Relational Data
* Multimedia Data
* Deep Learning

All of these require storing and processing high dimensional arrays efficiently.

We already learnt lists, sets, tuples and dictionaries.

List can store collection of high dimensional numbers as arrays and we can operate on them by iterating.
But this is very inefficient - 10x to 100x slower - than expected performance.

**Why?**
1. Lists are designed to store heterogenous data.
2. No low-level hardware mechanism to accelerate operations on lists


**Numpy**
* Intended to bring performance and functionality improvements for numerical computing
* Started only in 2006!
* Now a standard package used in many real-world apllications, other packages.

***Programing Level***
* provide implementation pof many functions across linear algebra, statistics...
* Efficiently broadcast operations across dimensions

***Functionality Level***
* Enable other packages to use numpy arrays as an efficient data interface 
* Efficiently process data without type-checking overhead.

***Hardware Level***
* Enable easy file save and load of n-d arrays.
* Efficiently store n-d array in vectorised form to benefit from DRAM locality.

**What we will focus on**
* What are nd-array?
* What is broadcasting?
* How to load and save n-d arrays
* How to use statistical functions.


## Comparing performance with lists, etc.

In [2]:
import numpy as np

In [3]:
N = 10000000

In [4]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 2.57 s, sys: 229 ms, total: 2.8 s
Wall time: 2.82 s


In [5]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 958 ms, sys: 457 ms, total: 1.42 s
Wall time: 1.43 s


In [6]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x*x , list_)

CPU times: user 332 ms, sys: 200 ms, total: 531 ms
Wall time: 528 ms


In [7]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum+=item

CPU times: user 1.37 s, sys: 153 ms, total: 1.52 s
Wall time: 1.52 s


In [8]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 226 ms, sys: 134 ms, total: 361 ms
Wall time: 360 ms


In [9]:
%%time
arr = np.arange(N)
arr = arr * arr


CPU times: user 32.8 ms, sys: 15.8 ms, total: 48.6 ms
Wall time: 53.7 ms


In [10]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 26.8 ms, sys: 936 µs, total: 27.7 ms
Wall time: 28.8 ms


## **High Dimensional Array & Creating NumPy Array**

In [11]:
arr = np.arange(5)

In [12]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [13]:
arr = np.array([0.0,2,4,6,8])

In [14]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [15]:
arr

array([0., 2., 4., 6., 8.])

In [16]:
arr.dtype

dtype('float64')

In [17]:
arr.ndim

1

In [18]:
arr.shape

(5,)

In [19]:
arr.size

5

In [20]:
arr.itemsize

8

In [21]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6]
])

In [22]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr2d.ndim

2

In [24]:
arr2d.shape

(2, 3)

In [25]:
arr2d.size

6

In [26]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])

In [27]:
arr3d.shape

(2, 2, 3)

In [28]:
arr3d.ndim

3

In [29]:
arr3d.size

12

In [30]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
1729*np.ones((2,3,4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [32]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
np.random.randn(2,3)

array([[ 0.58567715,  0.86858406,  0.3677976 ],
       [ 2.61436171, -2.06798593,  2.2369188 ]])

In [34]:
np.random.rand(2,3)

array([[0.38729069, 0.13326196, 0.08584172],
       [0.8841205 , 0.17001869, 0.73387666]])

In [35]:
np.random.rand(10,1)

array([[0.49238151],
       [0.05563022],
       [0.53804246],
       [0.42985418],
       [0.07267682],
       [0.99448542],
       [0.01356331],
       [0.93422725],
       [0.86662551],
       [0.22695496]])

In [36]:
np.random.randint(0, 100,(2,3))

array([[83, 25,  3],
       [74, 29, 45]])

In [37]:
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [38]:
np.linspace(7,70,10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [39]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [40]:
str_arr = np.array(['1.4','2.1','1.1'])

In [41]:
arr = np.array(str_arr, dtype = 'float')

In [42]:
arr

array([1.4, 2.1, 1.1])

## Creating np Arrays

In [43]:
import numpy as np

In [44]:
arr = np.arange(5)

In [45]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [46]:
arr.dtype

dtype('int64')

In [47]:
arr.ndim

1

In [48]:
arr.shape

(5,)

In [49]:
arr.size

5

In [50]:
arr.itemsize

8

In [51]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr2d.ndim

2

In [54]:
arr2d.shape

(2, 3)

In [55]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])

In [56]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d.shape

(2, 2, 3)

In [58]:
arr3d.size

12

In [59]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [60]:
1729*np.ones((2,3,4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [61]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [62]:
np.random.randn(2,3)

array([[-0.01225384,  0.59442731,  0.32310695],
       [ 0.27798455,  0.5914931 ,  0.01795523]])

In [63]:
np.random.rand(2,3)

array([[0.2392921 , 0.42908909, 0.70816473],
       [0.62575191, 0.60562154, 0.03392134]])

In [64]:
np.random.rand(10,1)

array([[0.1875118 ],
       [0.99873878],
       [0.98893499],
       [0.52207719],
       [0.94735219],
       [0.84976119],
       [0.45453098],
       [0.21097586],
       [0.19516398],
       [0.11717634]])

In [65]:
np.random.randint(0,100,(2,3))

array([[58, 69, 65],
       [11, 60, 61]])

In [66]:
np.arange(7,71,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [67]:
np.linspace(7, 70,10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [68]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [69]:
str_arr = np.array(['1.4','2.1','3.1'])

In [70]:
arr = np.array(str_arr, dtype = 'float')

In [71]:
arr

array([1.4, 2.1, 3.1])

## Indexing

In [72]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [73]:
arr3d[0,0,0]

1

In [74]:
arr3d[1,0,2]

9

In [75]:
i = 1
j = 0
k = 2
arr3d[i,j,k]

9

In [76]:
arr3d[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [77]:
arr3d[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [78]:
arr3d % 2 ==0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [80]:
arr3d[arr3d % 2 ==1]

array([ 1,  3,  5,  7,  9, 11])

In [81]:
arr3d[(arr3d % 2 ==1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [82]:
arr_slice = arr3d[:,:,0:2]

In [83]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [84]:
arr_slice.ndim

3

In [85]:
arr_slice.shape

(2, 2, 2)

In [86]:
arr_slice[0,0,1]

2

In [87]:
arr_slice[0,0,0] =1729

In [88]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [89]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [90]:
arr_slice = np.copy(arr3d[:,:,0:2])

In [91]:
arr_slice[0,0,0] =1

In [92]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [93]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [96]:
arr = np.random.randint(0,10, (5))

In [97]:
arr

array([4, 6, 2, 9, 7])

In [98]:
my_indices = [1,3,4]

In [99]:
arr[my_indices]

array([6, 9, 7])

## Numpy Operations